# Generated by Django 5.0.6 on 2026-04-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimchartrow",
            name="origin",
            field=models.CharField(
                choices=[("upload", "Original upload"), ("added", "Added to chart")],
                default="upload",
                max_length=20,
            ),
        ),
    ]
