# Generated by Django 5.0.6 on 2026-04-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0002_claimchartrow_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="rowchange",
            name="is_undone",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rowchange",
            name="redo_invalidated",
            field=models.BooleanField(
                default=False,
                help_text="True if a newer edit cleared the redo stack for this undone operation.",
            ),
        ),
        migrations.AddField(
            model_name="rowchange",
            name="undone_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
