# Generated by Django 5.0.6 on 2026-04-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0003_rowchange_undo_redo_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdoc",
            name="extracted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productdoc",
            name="extracted_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="productdoc",
            name="extracted_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
