# Generated by Django 5.0.6 on 2026-04-07 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assistant",
            "0004_productdoc_extracted_at_productdoc_extracted_error_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productdoc",
            name="claim_chart",
            field=models.ForeignKey(
                blank=True,
                help_text="Claim chart this technical / product doc supports (RAG context). Null = unassigned / legacy.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_docs",
                to="assistant.claimchart",
            ),
        ),
    ]
