# Generated by Django 5.0.6 on 2026-04-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0005_productdoc_claim_chart"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdoc",
            name="source_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="When set, this doc was captured from the web (no local file).",
                max_length=2048,
            ),
        ),
        migrations.AlterField(
            model_name="productdoc",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="product_docs/"),
        ),
    ]
