"""
Django settings for lumenci_assistant project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local environment variables from .env (prototype convenience).
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / ".env")
except Exception:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

import os

# Groq (strip whitespace — common typo when editing .env)
GROQ_API_KEY = (os.getenv("GROQ_API_KEY") or "").strip().strip('"').strip("'")
GROQ_MODEL = (os.getenv("GROQ_MODEL") or "llama-3.3-70b-versatile").strip()

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-insecure-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "1") in ("1", "true", "True", "yes", "YES")


def _env_csv(name: str, default: str) -> list[str]:
    """Split env on commas; strip whitespace and wrapping quotes (common copy/paste mistake)."""
    out: list[str] = []
    for part in (os.getenv(name, default) or "").split(","):
        s = (part or "").strip().strip('"').strip("'")
        if s:
            out.append(s)
    return out


# Hosts: DJANGO_ALLOWED_HOSTS and/or Render's RENDER_EXTERNAL_HOSTNAME / RENDER_EXTERNAL_URL.
_allowed_hosts = _env_csv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost")
_render_host = (os.getenv("RENDER_EXTERNAL_HOSTNAME") or "").strip().strip('"').strip("'")
if not _render_host:
    _ru = (os.getenv("RENDER_EXTERNAL_URL") or "").strip()
    if _ru:
        try:
            _render_host = (urlparse(_ru).hostname or "").strip()
        except Exception:
            _render_host = ""
if _render_host and _render_host not in _allowed_hosts:
    _allowed_hosts.append(_render_host)
ALLOWED_HOSTS = _allowed_hosts

# Behind Render's reverse proxy, Django should trust X-Forwarded-Proto for HTTPS URLs.
if _render_host:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Larger chart uploads (multipart body + file) — avoid 400/413 edge cases on Render.
DATA_UPLOAD_MAX_MEMORY_SIZE = min(
    int(os.getenv("DJANGO_DATA_UPLOAD_MAX_MB", "32") or "32") * 1024 * 1024,
    50 * 1024 * 1024,
)
FILE_UPLOAD_MAX_MEMORY_SIZE = min(
    int(os.getenv("DJANGO_FILE_UPLOAD_MAX_MB", "32") or "32") * 1024 * 1024,
    50 * 1024 * 1024,
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "assistant",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "lumenci_assistant.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lumenci_assistant.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Trusted origins for CSRF. Set DJANGO_CSRF_TRUSTED_ORIGINS=https://your.onrender.com (no extra quotes).
_csrf_origins = _env_csv("DJANGO_CSRF_TRUSTED_ORIGINS", "http://127.0.0.1:8000,http://localhost:8000")
if _render_host:
    for _scheme in ("https", "http"):
        _origin = f"{_scheme}://{_render_host}"
        if _origin not in _csrf_origins:
            _csrf_origins.append(_origin)
CSRF_TRUSTED_ORIGINS = _csrf_origins

# Media uploads (claim charts + product docs)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
